blueprint:
  name: Z2M - Ikea E2123
  description: "Zigbee2mqtt ikea E2123 blueprint for generic use."
  domain: automation
  input:
    remote:
      name: Remote
      description: "Remote to use"
      selector:
        entity:
          integration: mqtt
          domain: sensor

    toggle: #Only for version less then V1.0.35
      name: play
      description: "Action to run on play button press."
      default: []
      selector:
        action: {}

    play_pause: #Only for version V1.0.35
      name: play
      description: "Action to run on play button press."
      default: []
      selector:
        action: {}    

    track_next:
      name: track_next
      description: "Action to run on track next button press."
      default: []
      selector:
        action: {}

    track_previous:
      name: track_previous
      description: "Action to run on track previous button press."
      default: []
      selector:
        action: {}

    volume_up:
      name: volume_up
      description: "Action to run on volume up button press."
      default: []
      selector:
        action: {}

    volume_up_hold:
      name: volume_up_hold
      description: "Action to run on volume up button press hold."
      default: []
      selector:
        action: {}

    volume_down:
      name: volume_down
      description: "Action to run on volume down button press."
      default: []
      selector:
        action: {}

    volume_down_hold:
      name: volume_down_hold
      description: "Action to run on volume down button press hold."
      default: []
      selector:
        action: {}

    dots_1_initial_press:
      name: dots_1_initial_press
      description: "Action to run on dots 1 button press."
      default: []
      selector:
        action: {}
        
    dots_1_short_release: #Only for V1.0.35
      name: dots_1_short_release
      description: "Action to run on dots 1 button short press."
      default: []
      selector:
        action: {}
        
    dots_1_double_press:
      name: dots_1_double_press
      description: "Action to run on dots 1 button double press."
      default: []
      selector:
        action: {}
        
    dots_1_long_press:
      name: dots_1_long_press
      description: "Action to run on dots 1 button long press."
      default: []
      selector:
        action: {}
        
    dots_1_long_release: #Only for higher than V1.0.012
      name: dots_1_long_release
      description: "Action to run on dots 1 button long press release."
      default: []
      selector:
        action: {}
        
    dots_2_initial_press:
      name: dots_2_initial_press
      description: "Action to run on dots 2 button press."
      default: []
      selector:
        action: {}
        
    dots_2_short_release: #Only for V1.0.35
      name: dots_2_short_release
      description: "Action to run on dots 2 button short press."
      default: []
      selector:
        action: {}
        
    dots_2_double_press:
      name: dots_2_double_press
      description: "Action to run on dots 2 button double press."
      default: []
      selector:
        action: {}
        
    dots_2_long_press:
      name: dots_2_long_press
      description: "Action to run on dots 2 button long press."
      default: []
      selector:
        action: {}
        
    dots_2_long_release: #Only for higher than V1.0.012 
      name: dots_2_long_release
      description: "Action to run on dots 2 button long press release."
      default: []
      selector:
        action: {}
        
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote
    attribute: action

variables:
    command: "{{ trigger.to_state.state }}"

action:
  - choose:
    - conditions: #Only for version less then V1.0.35
        - "{{ command == 'toggle' }}"
      sequence: !input toggle

    - conditions: #Only for version V1.0.35
        - "{{ command == 'play_pause' }}"
      sequence: !input play_pause

    - conditions:
        - "{{ command == 'track_next' }}"
      sequence: !input track_next

    - conditions:
        - "{{ command == 'track_previous' }}"
      sequence: !input track_previous

    - conditions:
        - "{{ command == 'volume_up' }}"
      sequence: !input volume_up

    - conditions:
        - "{{ command == 'volume_up_hold' }}"
      sequence: !input volume_up_hold

    - conditions:
        - "{{ command == 'volume_down' }}"
      sequence: !input volume_down

    - conditions:
        - "{{ command == 'volume_down_hold' }}"
      sequence: !input volume_down_hold

    - conditions:
        - "{{ command == 'dots_1_initial_press' }}"
      sequence: !input dots_1_initial_press

    - conditions: #Only for V1.0.35
        - "{{ command == 'dots_1_short_release' }}"
      sequence: !input dots_1_short_release

    - conditions:
        - "{{ command == 'dots_1_double_press' }}"
      sequence: !input dots_1_double_press

    - conditions:
        - "{{ command == 'dots_1_long_press' }}"
      sequence: !input dots_1_long_press

    - conditions: #Only for higher than V1.0.012
        - "{{ command == 'dots_1_long_release' }}"
      sequence: !input dots_1_long_release

    - conditions:
        - "{{ command == 'dots_2_initial_press' }}"
      sequence: !input dots_2_initial_press

    - conditions: #Only for V1.0.35
        - "{{ command == 'dots_2_short_release' }}"
      sequence: !input dots_2_short_release

    - conditions:
        - "{{ command == 'dots_2_double_press' }}"
      sequence: !input dots_2_double_press

    - conditions:
        - "{{ command == 'dots_2_long_press' }}"
      sequence: !input dots_2_long_press

    - conditions: #Only for higher than V1.0.012
        - "{{ command == 'dots_2_long_release' }}"
      sequence: !input dots_2_long_release
